# Generated by Django 5.0.6 on 2024-05-17 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('', 'select one'), ('1', 'Mr'), ('2', 'Miss'), ('3', 'Mrs'), ('4', 'Miss'), ('5', 'Dr'), ('6', 'Prof')], max_length=50)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('sin_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_account', models.CharField(choices=[('', 'select one'), ('I', 'INVESTMENT'), ('R', 'REGISTERED'), ('T', 'TFSA')], default=[('', 'select one'), ('I', 'INVESTMENT'), ('R', 'REGISTERED'), ('T', 'TFSA')], max_length=50)),
                ('account_number', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='bankForm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross', models.CharField(max_length=255)),
                ('liquid_assets', models.CharField(max_length=255)),
                ('fixed_assets', models.CharField(max_length=255)),
                ('net_worth', models.CharField(max_length=255)),
                ('applicant_invest_knowledge', models.CharField(max_length=50)),
                ('coApplicant_investment_knowledge', models.CharField(max_length=50)),
                ('risk_tolerance', models.CharField(max_length=50)),
                ('time_horizon', models.CharField(max_length=255)),
                ('liquidity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('safety', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('long_term_growth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('short_term_growth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('speculation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inflation_hedging', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bankForm.customer')),
            ],
        ),
    ]
