# Generated by Django 5.0.6 on 2024-05-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankForm', '0002_customer_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='type_account',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='income',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='inflation_hedging',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='liquidity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='long_term_growth',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='safety',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='short_term_growth',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='speculation',
            field=models.CharField(max_length=10),
        ),
    ]
